FROM node:22.4.0-bookworm-slim
ENV SHELL="bash" PNPM_VERSION="9.4.0"
RUN apt-get --quiet --yes update \
    && apt-get --quiet --yes install --no-install-recommends git ca-certificates curl jq iputils-ping dnsutils netcat-traditional \
    && apt-get --quiet --yes autoremove \
    && rm --force --recursive /var/lib/apt/lists/ \
    && corepack enable \
    && corepack prepare pnpm@${PNPM_VERSION} --activate \
    && pnpm setup \
    && curl --retry 5 --location --output /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
    && chmod +x /usr/bin/yq
