FROM node:22.2.0-bookworm-slim
ENV SHELL=bash
RUN <<EOF
apt-get --quiet --yes update
apt-get --quiet --yes install --no-install-recommends git ca-certificates curl jq iputils-ping dnsutils netcat-traditional node-rimraf
curl --retry 5  --location https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 --output /usr/bin/yq && chmod +x /usr/bin/yq
apt-get --quiet --yes autoremove
rm --force --recursive /var/lib/apt/lists/
corepack enable
corepack prepare pnpm@9.3.0 --activate
pnpm setup
EOF
