FROM node:22.4.1-bookworm-slim
ENV SHELL="bash" PNPM_VERSION="9.5.0"
RUN apt-get update --quiet --yes \
    && apt-get install --quiet --yes --no-install-recommends \
        git \
        ca-certificates \
        curl \
        jq \
        iputils-ping \
        dnsutils \
        netcat-traditional \
    && apt-get autoremove --quiet --yes \
    && rm --force --recursive /var/lib/apt/lists/* \
    && corepack enable \
    && corepack prepare pnpm@${PNPM_VERSION} --activate \
    && pnpm setup \
    && curl --retry 5 --location --output /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
    && chmod +x /usr/bin/yq
